Repository wynn-rj/sword-and-bored-game, pull requests merged in 2020-02, with the labels that each got.

#98 Fix semicolon
  Assets/Scripts/Utilities/Random/ProbabilityTables/EqualProbabilityTable.cs
  Assets/Scripts/Utilities/Random/ProbabilityTables/WeightedProbabilityTable.cs
Labels: bug

#121 Add IsSetInEditor assert function
  Assets/Scripts/Utilities/Debug.meta
  Assets/Scripts/Utilities/Debug/AssertHelper.cs
  Assets/Scripts/Utilities/Debug/AssertHelper.cs.meta
Labels: enhancement

#142 New a star
  Assets/Scripts/Battlefield/MovementSystem.meta
  Assets/Scripts/Battlefield/MovementSystem/AStarBattlefieldMovementSystem.cs
  Assets/Scripts/Battlefield/MovementSystem/AStarBattlefieldMovementSystem.cs.meta
Labels: battlefield view, enhancement, high-priority
